// src/utils/reportBuilder.js
// Builds real, readable report files from live backend data.
//
// Excel/CSV → plain CSV (unchanged, opens directly in Excel/Sheets)
// PDF        → a genuine binary .pdf, built client-side with jsPDF
// anything else → formatted HTML (kept as a safe fallback)

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

function csvEscape(v) {
  const s = v === null || v === undefined ? '' : String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

function triggerDownload(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function safeName(name) {
  return (name || 'report').replace(/[^a-z0-9]+/gi, '_').replace(/^_+|_+$/g, '');
}

/* ────────────────────────────────────────────────────────────────────────
   CSV / Excel — unchanged
   ──────────────────────────────────────────────────────────────────────── */

export function downloadCSV(payload) {
  const { report, summary, students, predictions } = payload;
  const rows = [];

  rows.push(['EDUPREDICT REPORT']);
  rows.push([]);
  rows.push(['Report Name', report.name]);
  rows.push(['Report Type', report.type]);
  rows.push(['Date Range', report.date_range]);
  rows.push(['Generated By', report.generated_by]);
  rows.push(['Generated On', report.generated_on]);
  rows.push(['Description', report.description || '—']);
  rows.push([]);

  rows.push(['SUMMARY STATISTICS']);
  rows.push(['Metric', 'Value']);
  rows.push(['Total Students', summary.total_students]);
  rows.push(['High Performers', summary.high_performers]);
  rows.push(['High Risk Students', summary.high_risk]);
  rows.push(['Moderate Risk Students', summary.moderate_risk]);
  rows.push(['Low Risk Students', summary.low_risk]);
  rows.push(['Total Predictions Made', summary.total_predictions]);
  rows.push(['Average Predicted Grade (0-20)', summary.average_predicted_grade]);
  rows.push([]);

  rows.push(['STUDENT RECORDS']);
  rows.push(['Student ID', 'Name', 'Email', 'Grade', 'Performance', 'Risk Level', 'Confidence', 'Last Prediction']);
  if (students.length === 0) {
    rows.push(['No student records available']);
  } else {
    students.forEach((s) => rows.push([
      s.student_id, s.name, s.email, s.grade,
      s.performance || 'Not predicted', s.risk_level || '—',
      s.confidence || '—', s.last_prediction || '—',
    ]));
  }
  rows.push([]);

  rows.push(['PREDICTION HISTORY']);
  rows.push(['Student', 'Grade Level', 'Predicted Grade (0-20)', 'Performance', 'Risk Level', 'Confidence', 'Inputs Used', 'Predicted On']);
  if (predictions.length === 0) {
    rows.push(['No predictions recorded']);
  } else {
    predictions.forEach((p) => rows.push([
      p.student_name, p.grade_level || '—', p.predicted_grade,
      p.performance, p.risk_level, p.confidence,
      p.input_summary, p.predicted_on,
    ]));
  }
  rows.push([]);
  rows.push(['Generated by EduPredict — ML Student Performance Prediction System']);

  const csv = rows.map((r) => r.map(csvEscape).join(',')).join('\r\n');
  const blob = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' });
  triggerDownload(blob, `${safeName(report.name)}.csv`);
}

/* ────────────────────────────────────────────────────────────────────────
   PDF — real binary file via jsPDF + jspdf-autotable
   ──────────────────────────────────────────────────────────────────────── */

const INDIGO = [99, 102, 241];
const INDIGO_DARK = [67, 56, 202];
const GRAY_TEXT = [75, 85, 99];
const GRAY_LIGHT = [156, 163, 175];
const ROW_TINT = [248, 250, 252];

export function downloadPDF(payload) {
  const { report, summary, students, predictions } = payload;
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;
  let y = 40;

  const addFooter = () => {
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(...GRAY_LIGHT);
      doc.text(
        'EduPredict — ML Student Performance Prediction System',
        margin, doc.internal.pageSize.getHeight() - 22
      );
      doc.text(
        `Page ${i} of ${pageCount}`,
        pageWidth - margin, doc.internal.pageSize.getHeight() - 22,
        { align: 'right' }
      );
    }
  };

  // ── Header band ──────────────────────────────────────────────────────
  doc.setFillColor(...INDIGO);
  doc.rect(0, 0, pageWidth, 64, 'F');
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(margin, 14, 36, 36, 8, 8, 'F');
  doc.setTextColor(...INDIGO_DARK);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('E', margin + 18, 38, { align: 'center' });

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.text('EduPredict Report', margin + 48, 30);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text('ML Student Performance Prediction System', margin + 48, 44);
  y = 90;

  // ── Report details ───────────────────────────────────────────────────
  doc.setTextColor(...INDIGO_DARK);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Report Details', margin, y);
  y += 10;

  const details = [
    ['Report Name', report.name],
    ['Report Type', report.type],
    ['Date Range', report.date_range],
    ['Format', report.format],
    ['Generated By', report.generated_by],
    ['Generated On', report.generated_on],
  ];
  autoTable(doc, {
    startY: y,
    body: details,
    theme: 'plain',
    styles: { fontSize: 9, cellPadding: 3, textColor: GRAY_TEXT },
    columnStyles: {
      0: { fontStyle: 'bold', textColor: INDIGO_DARK, cellWidth: 120 },
    },
    margin: { left: margin, right: margin },
  });
  y = doc.lastAutoTable.finalY + 8;

  if (report.description) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(...GRAY_TEXT);
    const lines = doc.splitTextToSize(report.description, pageWidth - margin * 2);
    doc.text(lines, margin, y);
    y += lines.length * 12 + 6;
  }

  // ── Summary cards ─────────────────────────────────────────────────────
  y += 8;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...INDIGO_DARK);
  doc.text('Summary Statistics', margin, y);
  y += 12;

  const cards = [
    ['Total Students', summary.total_students],
    ['High Performers', summary.high_performers],
    ['High Risk', summary.high_risk],
    ['Avg Grade /20', summary.average_predicted_grade],
    ['Moderate Risk', summary.moderate_risk],
    ['Low Risk', summary.low_risk],
    ['Predictions Made', summary.total_predictions],
    ['Records Included', students.length],
  ];
  const cardW = (pageWidth - margin * 2 - 3 * 10) / 4;
  const cardH = 46;
  cards.forEach((c, i) => {
    const col = i % 4;
    const row = Math.floor(i / 4);
    const cx = margin + col * (cardW + 10);
    const cy = y + row * (cardH + 10);
    doc.setFillColor(245, 243, 255);
    doc.setDrawColor(224, 231, 255);
    doc.roundedRect(cx, cy, cardW, cardH, 6, 6, 'FD');
    doc.setTextColor(...INDIGO_DARK);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(15);
    doc.text(String(c[1]), cx + 10, cy + 22);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...GRAY_TEXT);
    doc.text(String(c[0]), cx + 10, cy + 35);
  });
  y += 2 * (cardH + 10) + 14;

  // ── Student records table ────────────────────────────────────────────
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...INDIGO_DARK);
  doc.text('Student Records', margin, y);
  y += 8;

  autoTable(doc, {
    startY: y,
    head: [['ID', 'Name', 'Email', 'Grade', 'Performance', 'Risk', 'Confidence', 'Last Prediction']],
    body: students.length === 0
      ? [['No student records available', '', '', '', '', '', '', '']]
      : students.map((s) => [
          s.student_id, s.name, s.email, s.grade,
          s.performance || 'Not predicted', s.risk_level || '—',
          s.confidence || '—', s.last_prediction || '—',
        ]),
    theme: 'striped',
    headStyles: { fillColor: INDIGO, textColor: 255, fontSize: 8, fontStyle: 'bold' },
    bodyStyles: { fontSize: 8, textColor: GRAY_TEXT },
    alternateRowStyles: { fillColor: ROW_TINT },
    margin: { left: margin, right: margin },
  });
  y = doc.lastAutoTable.finalY + 20;

  // ── Prediction history table ─────────────────────────────────────────
  if (y > doc.internal.pageSize.getHeight() - 120) {
    doc.addPage();
    y = 40;
  }
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...INDIGO_DARK);
  doc.text('Prediction History', margin, y);
  y += 8;

  autoTable(doc, {
    startY: y,
    head: [['Student', 'Grade Level', 'Predicted', 'Performance', 'Risk', 'Confidence', 'Predicted On']],
    body: predictions.length === 0
      ? [['No predictions recorded', '', '', '', '', '', '']]
      : predictions.map((p) => [
          p.student_name, p.grade_level || '—', `${p.predicted_grade}/20`,
          p.performance, p.risk_level, p.confidence, p.predicted_on,
        ]),
    theme: 'striped',
    headStyles: { fillColor: INDIGO, textColor: 255, fontSize: 8, fontStyle: 'bold' },
    bodyStyles: { fontSize: 8, textColor: GRAY_TEXT },
    alternateRowStyles: { fillColor: ROW_TINT },
    margin: { left: margin, right: margin },
  });

  addFooter();
  doc.save(`${safeName(report.name)}.pdf`);
}

/* ────────────────────────────────────────────────────────────────────────
   HTML — kept as a fallback for any format that isn't PDF or Excel/CSV
   ──────────────────────────────────────────────────────────────────────── */

export function downloadHTML(payload) {
  const { report, summary, students, predictions } = payload;

  const esc = (v) => String(v ?? '—')
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

  const studentRows = students.length === 0
    ? '<tr><td colspan="8" class="empty">No student records available</td></tr>'
    : students.map((s) => `<tr>
        <td>${esc(s.student_id)}</td><td>${esc(s.name)}</td><td>${esc(s.email)}</td>
        <td>${esc(s.grade)}</td><td>${esc(s.performance || 'Not predicted')}</td>
        <td>${esc(s.risk_level)}</td><td>${esc(s.confidence)}</td><td>${esc(s.last_prediction)}</td>
      </tr>`).join('');

  const predRows = predictions.length === 0
    ? '<tr><td colspan="7" class="empty">No predictions recorded</td></tr>'
    : predictions.map((p) => `<tr>
        <td>${esc(p.student_name)}</td><td>${esc(p.grade_level)}</td>
        <td><strong>${esc(p.predicted_grade)}</strong>/20</td>
        <td>${esc(p.performance)}</td><td>${esc(p.risk_level)}</td>
        <td>${esc(p.confidence)}</td><td>${esc(p.predicted_on)}</td>
      </tr>`).join('');

  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>${esc(report.name)} — EduPredict</title>
<style>
  *{box-sizing:border-box}
  body{font-family:'Segoe UI',Arial,sans-serif;color:#1f2937;margin:0;padding:40px;background:#f9fafb}
  .sheet{max-width:1000px;margin:0 auto;background:#fff;padding:40px;border-radius:12px;box-shadow:0 1px 3px rgba(0,0,0,.08)}
  .brand{display:flex;align-items:center;gap:12px;border-bottom:3px solid #6366F1;padding-bottom:16px;margin-bottom:24px}
  .logo{width:40px;height:40px;border-radius:10px;background:linear-gradient(135deg,#6366F1,#4F46E5);color:#fff;
        display:flex;align-items:center;justify-content:center;font-weight:800;font-size:20px}
  h1{margin:0;font-size:22px}
  .sub{color:#6b7280;font-size:12px;margin-top:2px}
  h2{font-size:15px;margin:28px 0 10px;color:#4338ca;text-transform:uppercase;letter-spacing:.5px}
  .meta{display:grid;grid-template-columns:repeat(2,1fr);gap:8px 24px;font-size:13px;margin-bottom:8px}
  .meta div{padding:6px 0;border-bottom:1px solid #f3f4f6}
  .meta span{color:#6b7280;display:inline-block;min-width:120px}
  .cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:14px 0}
  .card{background:#f5f3ff;border:1px solid #e0e7ff;border-radius:10px;padding:14px}
  .card .n{font-size:22px;font-weight:800;color:#4338ca}
  .card .l{font-size:11px;color:#6b7280;margin-top:2px}
  table{width:100%;border-collapse:collapse;font-size:12px;margin-top:6px}
  th{background:#eef2ff;color:#3730a3;text-align:left;padding:9px;border:1px solid #e0e7ff;font-weight:700}
  td{padding:8px 9px;border:1px solid #f1f5f9}
  tr:nth-child(even) td{background:#fafafa}
  .empty{text-align:center;color:#9ca3af;font-style:italic;padding:20px}
  footer{margin-top:32px;padding-top:14px;border-top:1px solid #e5e7eb;color:#9ca3af;font-size:11px;text-align:center}
  @media print{body{background:#fff;padding:0}.sheet{box-shadow:none;padding:16px}}
</style></head><body><div class="sheet">
  <div class="brand">
    <div class="logo">E</div>
    <div><h1>EduPredict Report</h1><div class="sub">ML Student Performance Prediction System</div></div>
  </div>

  <h2>Report Details</h2>
  <div class="meta">
    <div><span>Report Name</span> <strong>${esc(report.name)}</strong></div>
    <div><span>Report Type</span> ${esc(report.type)}</div>
    <div><span>Date Range</span> ${esc(report.date_range)}</div>
    <div><span>Format</span> ${esc(report.format)}</div>
    <div><span>Generated By</span> ${esc(report.generated_by)}</div>
    <div><span>Generated On</span> ${esc(report.generated_on)}</div>
  </div>
  ${report.description ? `<p style="font-size:13px;color:#4b5563">${esc(report.description)}</p>` : ''}

  <h2>Summary Statistics</h2>
  <div class="cards">
    <div class="card"><div class="n">${summary.total_students}</div><div class="l">Total Students</div></div>
    <div class="card"><div class="n">${summary.high_performers}</div><div class="l">High Performers</div></div>
    <div class="card"><div class="n">${summary.high_risk}</div><div class="l">High Risk</div></div>
    <div class="card"><div class="n">${summary.average_predicted_grade}</div><div class="l">Avg Grade /20</div></div>
  </div>
  <div class="cards">
    <div class="card"><div class="n">${summary.moderate_risk}</div><div class="l">Moderate Risk</div></div>
    <div class="card"><div class="n">${summary.low_risk}</div><div class="l">Low Risk</div></div>
    <div class="card"><div class="n">${summary.total_predictions}</div><div class="l">Predictions Made</div></div>
    <div class="card"><div class="n">${students.length}</div><div class="l">Records Included</div></div>
  </div>

  <h2>Student Records</h2>
  <table><thead><tr>
    <th>Student ID</th><th>Name</th><th>Email</th><th>Grade</th>
    <th>Performance</th><th>Risk Level</th><th>Confidence</th><th>Last Prediction</th>
  </tr></thead><tbody>${studentRows}</tbody></table>

  <h2>Prediction History</h2>
  <table><thead><tr>
    <th>Student</th><th>Grade Level</th><th>Predicted Grade</th>
    <th>Performance</th><th>Risk Level</th><th>Confidence</th><th>Predicted On</th>
  </tr></thead><tbody>${predRows}</tbody></table>

  <footer>
    Generated by EduPredict — ML Student Performance Prediction System<br>
    Random Forest Regressor · R² = 0.83 · MAE = 0.91 · Trained on 1,044 student records
  </footer>
</div></body></html>`;

  const blob = new Blob([html], { type: 'text/html;charset=utf-8;' });
  triggerDownload(blob, `${safeName(report.name)}.html`);
}

/* ────────────────────────────────────────────────────────────────────────
   Router — picks the builder based on the report's chosen format
   ──────────────────────────────────────────────────────────────────────── */

export function downloadReportFile(payload) {
  const fmt = (payload?.report?.format || 'PDF').toLowerCase();
  if (fmt === 'excel' || fmt === 'csv') downloadCSV(payload);
  else if (fmt === 'pdf') downloadPDF(payload);
  else downloadHTML(payload);
}
